apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: charging-attendant
spec:
  tls:
    - hosts:
      - ev-backend.charging-attendant.com
      - charging-attendant.com
      secretName: tls-secret
  rules:
    - http:
        paths:
        - backend:
            serviceName: ev-backend-service
            servicePort: 8080
