apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  labels:
    run: ev-backend
  name: ev-backend
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      run: ev-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        redeploy: "1574553112"
        run: ev-backend
    spec:
      containers:
        - image: gcr.io/elite-droplet-256314/chargeattendant/ev-backend:latest
          imagePullPolicy: Always
          name: ev-backend
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - name: ev-backend-port
              containerPort: 8080
              hostPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: ev-backend-port
            initialDelaySeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: ev-backend-port
            initialDelaySeconds: 5
            periodSeconds: 10

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
